
nwo.Map.maps.push({
    name: 'map1',
    map: [
        '                                                                                          ',
        '                                                                                          ',
        '                                                           ~~~~~~~~~~~~~~~~~~~~~~         ',
        '                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~       ',
        '            LLLL                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~       ',
        '              LLLL                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~          ',
        '                                                       ~~~~~~~~~~~~~~~~~~~~~~~~           ',
        '                                                                 ~~~~~~~~~~~~             ',
        '                                                                                          ',
        '                                                                                          ',
        '                                                                                          ',
        '               HHHH                                                                       ',
        '                HHHH                                                                      ',
        '                 HHHH                                                                     ',
        '                                                                                          ',
        '                                                                                          ',
        '                                                                                          ',
        '                                                                                          ',
        '                                                                                          ',
        '                                                                                          ',
        '                                                                                          ',
        '                                                                  LLLLLL                  ',
        '                                                               LLLLLLLLLLLL               ',
        '                                                                  LLLLLLLLLLLLLLLLLLLLL   ',
        '         HHHHHHHHHHH                                                 LLLLLLLLLLLLLL       ',
        '     HHHHHHHHHHHH                                                     LLLLLLLLLLLLLLLL    ',
        '   HHHHHHHHHHH                                                         LLLLLLLLLLLLLLLLLLL',
        ' HHHHHHHHH                                                              LLLLLLLLLLLLLLLLLL',
        'HHHHHH                                                              LLLLLLLLLLLLLLLLLLLL  ',
        '                                                                   LLLLLLLLLLLLLLLLLLLLLLL',
        '                                                          LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL ',
        '                                                   LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL       ',
        '                                           LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL       '
    ]
});
